CXX = g++
CXXFLAGS = -g

ProbeHashTable.o: ProbeHashTable.cpp ProbeHashTable.h
	$(CXX) $(CXXFLAGS) -c ProbeHashTable.cpp

ChainHashTable.o: ChainHashtable.cpp ChainHashTable.h
	$(CXX) $(CXXFLAGS) -c ChainHashTable.cpp

getCurrentCPU.o: getCurrentCPU.cpp getCurrentCPU.h
	$(CXX) $(CXXFLAGS) -c getCurrentCPU.cpp

clean:
	rm *.o
	rm *~
